import Link from 'next/link';
import { ContentSection } from '../../components/content-section';
import { PageFrame } from '../../components/page-frame';
import { PageIntro } from '../../components/page-intro';
import { pageMetadata } from '../../lib/metadata';
export const metadata = pageMetadata('/editorial-policy/');
export default function Page() {
  return <PageFrame breadcrumbPath="/editorial-policy/"><PageIntro eyebrow="ToolPilot / Trust" title={"Methodology"} summary={"How we source, evaluate and review developer-tool research."}/>
      <ContentSection><h2>Sources and evidence</h2><p>We prioritize official product documentation, current pricing pages and public vendor repositories. Each factual field has its own source and reading date. Missing information is marked unknown. Successful HTTP access only establishes link reachability, not that a product claim is accurate.</p></ContentSection>
      <ContentSection><h2>Pricing verification</h2><p>Prices are recorded with the plan, billing interval, allowance and other available terms shown by the source. A displayed base price is not a complete operating-cost estimate. Where account, region, tax, usage or checkout details are unavailable, they remain explicit limitations for the reader to confirm.</p></ContentSection>
      <ContentSection><h2>Feature verification</h2><p>Feature claims are checked against cited product documentation or other identified official sources. A missing source stays unknown; it is not treated as proof that a feature is absent. We do not convert a successful link check into feature verification.</p></ContentSection>
      <ContentSection><h2>Testing methodology</h2><p>A hands-on claim requires a documented test, date and reproducible conditions. Suggested trial procedures are instructions for readers, not tests ToolPilot has performed. This version publishes no benchmark results or hands-on test claims.</p></ContentSection>
      <ContentSection><h2>Selection and rankings</h2><p>Comparisons and shortlists are organized around a stated task and the evidence or constraints relevant to that task. We describe who a candidate may fit, where it may not, and conditions that could change the choice. Candidate order is not a universal score or measured performance ranking. We do not declare a winner when the available evidence cannot support one. Commercial relationships do not determine selection, conclusions or natural ordering.</p></ContentSection>
      <ContentSection><h2>Review and update timing</h2><p>Research drafts await the site owner’s approval. Formal approval applies to one content revision. Material changes to price, features, sources, relationships or conclusions require review again, including dependent comparisons. The freshness checker places price fields in a review queue after 30 days and other factual fields after 90 days. These are review thresholds, not a fixed publishing cadence, automatic verification or a guarantee that every vendor change is detected. Historical research is retained separately from the current public profile.</p></ContentSection>
      <ContentSection><h2>Corrections</h2><p>For a correction, identify the page, the disputed statement, an official source and the date it changed. Our public contact channel is still being finalized. Do not send account credentials or private customer records. Critical factual errors require withdrawing the affected recommendation while it is reviewed.</p></ContentSection>
      <ContentSection><h2>Commercial independence</h2><p>Affiliate links, featured placements and sponsorships are distinct. Commercial payments do not determine factual verification, comparison conclusions or natural ordering. Vendor descriptions are inputs to review, not independent evaluations.</p></ContentSection>
      <ContentSection><p><Link href="/editorial-policy/">Methodology</Link> · <Link href="/disclosure/">Affiliate Disclosure</Link> · <Link href="/contact/">Contact</Link></p></ContentSection>
    </PageFrame>;
}
