export type ReviewState = "draft" | "in-review" | "published";
export type Source = { id: string; url: string; title: string; publisher: string; accessedAt: string };
export type Fact = { key: string; label: string; value: string | null; sourceIds: string[]; checkedAt: string | null; critical: boolean };
export type Price = { name: string; amount: number | null; currency: string; interval: string; billing: string; allowance: string | null; overage: string | null; taxes: string | null; sourceIds: string[]; checkedAt: string | null };
export type Section = { heading: string; paragraphs: string[] };
export type SourceReference = { toolSlug: string; sourceId: string };
export type EvidenceClaim = { text: string; sourceRefs: SourceReference[] };
export type EvidenceFaq = { question: string; answer: string; sourceRefs: SourceReference[] };
export type RelatedLink = { kind: Content["kind"]; slug: string };
export type CommercialRelation = { status: "unconfirmed" | "none" | "active"; url: string | null; disclosure: string | null; evidence: string | null };
export type Content = {
  slug: string; kind: "tools" | "compare" | "alternatives" | "pricing" | "best" | "guides";
  title: string; summary: string; revision: number; updatedAt: string;
  review: { state: ReviewState; owner: string | null; reviewedAt: string | null; approvedRevision: number | null; approvedDigest: string | null; evidence: string | null };
  verifiedAt: string | null; testedAt: string | null; testEvidence: string | null;
  sources: Source[]; facts: Fact[]; prices: Price[]; sections: Section[];
  pros?: EvidenceClaim[]; cons?: EvidenceClaim[]; faqs?: EvidenceFaq[];
  relatedLinks?: RelatedLink[];
  verdict: string; bestFor: string; notFor: string; migration: string;
  dependencies: { slug: string; revision: number; digest: string }[]; gaps: string[];
  changes: { date: string; summary: string }[];
  commercial: { affiliate: CommercialRelation; featured: CommercialRelation; sponsor: CommercialRelation };
  name?: string; category?: string; productUrl?: string;
};
export type PublicTool = { slug: string; name: string; category: string; summary: string; bestFor: string; status: string; productUrl: string };
